### ISSUE TITLE
this example (Celery_Redis_with_Django.md) can not run on windows

### ISSUE THREAD

**Issue by miguelveces** [codingforentrepreneurs/Guides#9]
I run this example and I get following error on windows:

[2016-11-23 14:01:44,552: CRITICAL/MainProcess] Unrecoverable error: AttributeError("Can't pickle local object 'Pool.__init__.<locals>.Process'",)
Traceback (most recent call last):
  File "c:\python_environments\pmp_shield_env_veces\lib\site-packages\celery\worker\worker.py", line 203, in start
    self.blueprint.start(self)
  File "c:\python_environments\pmp_shield_env_veces\lib\site-packages\celery\bootsteps.py", line 119, in start
    step.start(parent)
  File "c:\python_environments\pmp_shield_env_veces\lib\site-packages\celery\bootsteps.py", line 370, in start
    return self.obj.start()
  File "c:\python_environments\pmp_shield_env_veces\lib\site-packages\celery\concurrency\base.py", line 131, in start
    self.on_start()
  File "c:\python_environments\pmp_shield_env_veces\lib\site-packages\celery\concurrency\prefork.py", line 112, in on_start
    **self.options)
  File "c:\python_environments\pmp_shield_env_veces\lib\site-packages\billiard\pool.py", line 1008, in __init__
    self._create_worker_process(i)
  File "c:\python_environments\pmp_shield_env_veces\lib\site-packages\billiard\pool.py", line 1117, in _create_worker_process
    w.start()
  File "c:\python_environments\pmp_shield_env_veces\lib\site-packages\billiard\process.py", line 122, in start
    self._popen = self._Popen(self)
  File "c:\python_environments\pmp_shield_env_veces\lib\site-packages\billiard\context.py", line 383, in _Popen
    return Popen(process_obj)
  File "c:\python_environments\pmp_shield_env_veces\lib\site-packages\billiard\popen_spawn_win32.py", line 79, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\python_environments\pmp_shield_env_veces\lib\site-packages\billiard\reduction.py", line 99, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Pool.__init__.<locals>.Process'

(wat) C:\ProjectDjango\celeryTest\src>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python_environments\pmp_shield_env_veces\lib\site-packages\billiard\spawn.py", line 159, in spawn_main
    new_handle = steal_handle(parent_pid, pipe_handle)
  File "c:\python_environments\pmp_shield_env_veces\lib\site-packages\billiard\reduction.py", line 126, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied

**Comment by bobony** [comment]
Can you run it as an administrator

**Comment by bobony** [comment]
As this thread is not active and hoping the issue as fixed. Closing the issue.
